version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_NAME}
    env_file:
      - .env
    volumes:
      - mongodb:/data/db
    ports:
      - '6000:27017'

  app:
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo

volumes:
  mongodb:
